#PROGRAM TO CALCULATE REMAINING BALANCE AFTER WITHDRAWAL

#INPUT CURRENT BALANCE AND WITHRAWAL AMOUNT
CB=float(input("Enter current Balance: "))
WA=int(input("Enter Withdrawal Amount: "))

#REMAINING BALACNE
REMAINING_BALANCE=CB-WA;

#OUTPUT
print("REMAINING BALANC: " ,REMAINING_BALANCE)

