# PROGRAM TO CALCULATE COMPANY SALARY 

#INPUT BASIC SALARY AND INCENTIVE
BS=int(input("Enter basic Salary"))
IN=int(input("Incentive"))
#CALCULATE TOTAL SALARY
TOTAL_SALARY=BS+IN;
#OUTPUT 
print(TOTAL_SALARY)


